BEGIN BEGIN EXECUTE IMMEDIATE 'DROP TABLE utilisateurs_statique CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE utilisateurs_dynamique CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE service CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE localisation CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE date_aws CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE mode_facturation CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE ressource CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE agent CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE heure CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE statut CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE processus CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; END;
/

-- =============================================
------------------ DIMENSIONS ------------------
-- =============================================

-- CREATE TABLE utilisateurs (
--     id_utilisateur NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
--     type_utilisateur VARCHAR(50),
--     nom_famille VARCHAR(100),
--     prenom VARCHAR(100),
--     sexe VARCHAR(10),
--     date_de_naissance DATE,
--     nom_legal VARCHAR(200),
--     numero_identification VARCHAR(50),
--     secteur_activite VARCHAR(100),
--     email VARCHAR(100),
--     telephone VARCHAR(20),
--     pays_utilisateur VARCHAR(50),
--     date_inscription DATE,
--     CONSTRAINT pk_utilisateurs PRIMARY KEY (id_utilisateur)
-- )
-- ;

CREATE TABLE utilisateurs_statique (
    id_utilisateur NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    type_utilisateur VARCHAR(50),
    nom_famille VARCHAR(100),
    prenom VARCHAR(100),
    sexe VARCHAR(10),
    date_de_naissance DATE,
    nom_legal VARCHAR(200),
    numero_identification VARCHAR(50),
    date_inscription DATE,
    CONSTRAINT pk_utilisateurs_statique PRIMARY KEY (id_utilisateur)
)
;

CREATE TABLE utilisateurs_dynamique (
    id_utilisateur NUMBER(20),
    secteur_activite VARCHAR(100),
    email VARCHAR(100),
    telephone VARCHAR(20),
    pays_utilisateur VARCHAR(50),
    date_debut DATE DEFAULT SYSDATE NOT NULL,
    date_fin DATE DEFAULT TO_DATE('9999-01-01', 'YYYY-MM-DD'),
    est_actif CHAR(1) DEFAULT 'Y',
    CONSTRAINT pk_utilisateurs_dynamique PRIMARY KEY (id_utilisateur, date_debut)
)
    PARTITION BY LIST (pays_utilisateur)
    SUBPARTITION BY LIST (secteur_activite)
    SUBPARTITION TEMPLATE (
        SUBPARTITION sous_parition_tech VALUES ('TECHNOLOGY'),
        SUBPARTITION sous_parition_media VALUES ('MEDIA'),
        SUBPARTITION sous_parition_finance VALUES ('FINANCE'),
        SUBPARTITION sous_parition_retail VALUES ('RETAIL'),
        SUBPARTITION sous_parition_health VALUES ('HEALTHCARE'),
        SUBPARTITION sous_parition_other_sectors VALUES (DEFAULT)
    )
    (
        -- 5 pays avec le plus de clients AWS
        PARTITION partition_usa VALUES ('USA'),
        PARTITION partition_india VALUES ('INDIA'),
        PARTITION partition_japan VALUES ('JAPAN'),
        PARTITION partition_uk VALUES ('UK'),
        PARTITION partition_germany VALUES ('GERMANY'),
        PARTITION partition_autres_pays VALUES (DEFAULT)
    )
;

CREATE TABLE service (
    id_service NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    code_service VARCHAR(50),
    nom_service VARCHAR(100),
    categorie VARCHAR(100),
    famille_service VARCHAR(100),
    statut_service VARCHAR(50),
    CONSTRAINT pk_service PRIMARY KEY (id_service)
);

CREATE TABLE localisation (
    id_localisation NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    ville VARCHAR(100),
    code_ville VARCHAR(20),
    departement_province VARCHAR(100),
    pays VARCHAR(100),
    continent VARCHAR(100),
    fuseau_horraire VARCHAR(50),
    code_az VARCHAR(50),
    nom_az VARCHAR(100),
    CONSTRAINT pk_localisation PRIMARY KEY (id_localisation)
);

CREATE TABLE mode_facturation (
    id_mode_facturation NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    code_mode_facturation VARCHAR(50),
    unite_mesure VARCHAR(50),
    categorie_usage VARCHAR(100),
    methode_paiement VARCHAR(50),
    CONSTRAINT pk_mode_facturation PRIMARY KEY (id_mode_facturation)
);

CREATE TABLE ressource (
    id_ressource NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    nom_ressource VARCHAR(100),
    type_ressource VARCHAR(100),
    statut_ressource VARCHAR(50),
    DT_mise_en_route DATE,
    DT_derniere_maintenance DATE,
    DT_fin_service DATE,
    IP VARCHAR(45),
    OS VARCHAR(50),
    data_center VARCHAR(100),
    CONSTRAINT pk_ressource PRIMARY KEY (id_ressource)
);

CREATE TABLE agent (
    id_agent NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    matricule VARCHAR(50),
    nom_agent VARCHAR(100),
    prenom_agent VARCHAR(100),
    equipe VARCHAR(100),
    niveau_support VARCHAR(50),
    sexe VARCHAR(10),
    date_de_naissance DATE,
    email VARCHAR(100),
    telephone VARCHAR(20),
    date_entree DATE,
    nb_pause_toilette NUMBER(5),
    CONSTRAINT pk_agent PRIMARY KEY (id_agent)
);

CREATE TABLE statut (
    id_statut NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    nom_statut VARCHAR(100),
    CONSTRAINT pk_statut PRIMARY KEY (id_statut)
);

CREATE TABLE processus (
    id_processus NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    nom_processus VARCHAR(200),
    type_processus VARCHAR(100),
    chemin VARCHAR(500),
    version VARCHAR(30),
    criticite VARCHAR(50),
    CONSTRAINT pk_processus PRIMARY KEY (id_processus)
);

CREATE TABLE date_aws (
    id_date NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    date_complete DATE,
    numero_jour NUMBER(2),
    jour VARCHAR(20),
    numero_mois NUMBER(2),
    mois VARCHAR(20),
    trimestre NUMBER(1),
    annee NUMBER(4),
    jour_semaine VARCHAR(20),
    est_weekend CHAR(1),
    jour_ferie CHAR(1),
    numero_semaine_annee NUMBER(2),
    CONSTRAINT pk_date PRIMARY KEY (id_date)
);

CREATE TABLE heure (
    id_heure NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
    heure_complete VARCHAR(8),
    heure_minute VARCHAR(5),
    heure NUMBER(2),
    minute NUMBER(2),
    seconde NUMBER(2),
    periode_journee VARCHAR(50),
    est_heure_ouvrable CHAR(1),
    CONSTRAINT pk_heure PRIMARY KEY (id_heure)
);

-- =========================================
------------------ Faits -------------------
-- =========================================

BEGIN BEGIN EXECUTE IMMEDIATE 'DROP TABLE facturation CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE actifs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE incident CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; BEGIN EXECUTE IMMEDIATE 'DROP TABLE monitoring CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; END;
/

CREATE TABLE facturation (
    id_utilisateur NUMBER(20),
    id_service NUMBER(20),
    id_localisation NUMBER(20),
    id_date NUMBER(20),
    id_mode_facturation NUMBER(20),
    total_brute NUMBER(18, 2),
    total_taxe NUMBER(18, 2),
    remise NUMBER(18, 2),
    total_net NUMBER(18, 2),
    quantite_consommee NUMBER(15, 3),
    prix_unitaire NUMBER(18, 4),
    CONSTRAINT pk_facturation PRIMARY KEY (id_utilisateur, id_service, id_localisation, id_date, id_mode_facturation),
    CONSTRAINT fk_facturation_utilisateurs FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur),
    CONSTRAINT fk_facturation_service FOREIGN KEY (id_service) REFERENCES service (id_service),
    CONSTRAINT fk_facturation_localisation FOREIGN KEY (id_localisation) REFERENCES localisation (id_localisation),
    CONSTRAINT fk_facturation_date FOREIGN KEY (id_date) REFERENCES date_aws (id_date),
    CONSTRAINT fk_facturation_mode_facturation FOREIGN KEY (id_mode_facturation) REFERENCES mode_facturation (id_mode_facturation)
);

CREATE TABLE actifs (
    id_service NUMBER(20),
    id_localisation NUMBER(20),
    id_ressource NUMBER(20),
    id_date NUMBER(20),
    cout_total NUMBER(18, 2),
    cout_electricite NUMBER(18, 2),
    cout_maintenance NUMBER(18, 2),
    cout_materiel NUMBER(18, 2),
    cout_personnel NUMBER(18, 2),
    cout_theorique_max NUMBER(18, 2),
    CONSTRAINT pk_actifs PRIMARY KEY (id_service, id_localisation, id_ressource, id_date),
    CONSTRAINT fk_actifs_service FOREIGN KEY (id_service) REFERENCES service (id_service),
    CONSTRAINT fk_actifs_localisation FOREIGN KEY (id_localisation) REFERENCES localisation (id_localisation),
    CONSTRAINT fk_actifs_ressource FOREIGN KEY (id_ressource) REFERENCES ressource (id_ressource),
    CONSTRAINT fk_actifs_date FOREIGN KEY (id_date) REFERENCES date_aws (id_date)
);

CREATE TABLE incident (
    id_incident NUMBER(20),
    id_utilisateur_responsable NUMBER(20),
    id_agent NUMBER(20),
    id_localisation NUMBER(20),
    id_ressource NUMBER(20),
    id_date NUMBER(20),
    id_heure NUMBER(20),
    id_statut NUMBER(20),
    cout_agent NUMBER(18,2),
    cout_remboursement_estime NUMBER(18,2),
    cout_client_estime NUMBER(18,2),
    nb_utilisateurs_impactes NUMBER(18,2),
    CONSTRAINT pk_incident PRIMARY KEY (id_incident, id_utilisateur_responsable, id_agent, id_localisation, id_ressource, id_date, id_heure, id_statut),
    CONSTRAINT fk_incident_utilisateurs FOREIGN KEY (id_utilisateur_responsable) REFERENCES utilisateurs (id_utilisateur),
    CONSTRAINT fk_incident_agent FOREIGN KEY (id_agent) REFERENCES agent (id_agent),
    CONSTRAINT fk_incident_localisation FOREIGN KEY (id_localisation) REFERENCES localisation (id_localisation),
    CONSTRAINT fk_incident_ressource FOREIGN KEY (id_ressource) REFERENCES ressource (id_ressource),
    CONSTRAINT fk_incident_date FOREIGN KEY (id_date) REFERENCES date_aws (id_date),
    CONSTRAINT fk_incident_heure FOREIGN KEY (id_heure) REFERENCES heure (id_heure),
    CONSTRAINT fk_incident_statut FOREIGN KEY (id_statut) REFERENCES statut (id_statut)
);

CREATE TABLE monitoring (
    id_utilisateur NUMBER(20),
    id_ressource NUMBER(20),
    id_processus NUMBER(20),
    id_service NUMBER(20),
    id_date NUMBER(20),
    id_heure NUMBER(20),
    CPU_utilisation NUMBER(5),
    GPU_utilisation NUMBER(5),
    RPM_ventilateur NUMBER(10),
    RPM_GPU_ventilateur NUMBER(10),
    est_actif NUMBER(1),
    temps_total_actif NUMBER(10),
    temperature NUMBER(5),
    nb_core_utilises NUMBER(5),
    nb_threads_utilises NUMBER(10),
    CONSTRAINT pk_monitoring PRIMARY KEY (id_utilisateur, id_ressource, id_processus, id_service, id_date, id_heure),
    CONSTRAINT fk_monitoring_utilisateurs FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id_utilisateur),
    CONSTRAINT fk_monitoring_ressource FOREIGN KEY (id_ressource) REFERENCES ressource (id_ressource),
    CONSTRAINT fk_monitoring_processus FOREIGN KEY (id_processus) REFERENCES processus (id_processus),
    CONSTRAINT fk_monitoring_service FOREIGN KEY (id_service) REFERENCES service (id_service),
    CONSTRAINT fk_monitoring_date FOREIGN KEY (id_date) REFERENCES date_aws (id_date),
    CONSTRAINT fk_monitoring_heure FOREIGN KEY (id_heure) REFERENCES heure (id_heure)
);